[[plugins]]
repo = 'vim-denops/denops.vim'

[[plugins]]
repo = 'altercation/vim-colors-solarized'

[[plugins]]
repo = 'Shougo/context_filetype.vim'

[[plugins]]
repo = 'itchyny/lightline.vim'
hook_add = '''
  execute 'source ' . g:dein_plugin_rc . '/lightline.rc.vim'
'''
