# lxd
# Autogenerated from man page /usr/share/man/man1/lxd.1.gz
complete -c lxd -l cpu-profile --description '	Enable CPU profiling, writing into the specified file``.'
complete -c lxd -s d -l debug --description '	Show all debug messages.'
complete -c lxd -l group --description '	The group of users that will be allowed to talk to LXD``.'
complete -c lxd -s h -l help --description '	Print help.'
complete -c lxd -l logfile --description '	Path to the log file``.'
complete -c lxd -l memory-profile --description '	Enable memory profiling, writing into the specified file``.'
complete -c lxd -l print-goroutines --description '	How often to print all the goroutines``.'
complete -c lxd -l trace --description '	Log tracing targets``.'
complete -c lxd -s v -l verbose --description '	Show all information messages.'
complete -c lxd -l version --description '	Print version number SEE ALSO.'

