# unattended-upgrades
# Autogenerated from man page /usr/share/man/man8/unattended-upgrades.8.gz
complete -c unattended-upgrades -s h -l help --description 'help output.'
complete -c unattended-upgrades -s d -l debug --description 'extra debug output into /var/log/unattended-upgrades. log.'
complete -c unattended-upgrades -l dry-run --description 'Just simulate installing updates, do not actually do it CONFIGURATION The con…'

