[[plugins]]
repo = 'cespare/vim-toml'
on_ft = 'toml'

[[plugins]]
repo = 'PieterjanMontens/vim-pipenv'
on_ft = 'python'
depends = ['vim-virtualenv']

[[plugins]]
repo = 'jmcantrell/vim-virtualenv'

[[plugins]]
repo = 'hirsaeki-mki/ansible-vim'
on_path = [
  '.*\.yml',
  '.*\.j2',
  'hosts',
  'inventory'
]

[[plugins]]
repo = 'b4b4r07/vim-ansible-vault'
on_ft = [
  'yaml.ansible',
]

[[plugins]]
repo ='Shougo/denite.nvim'
depends = ['neomru.vim']
on_cmd = 'Denite'
hook_source = '''
  execute 'source ' . g:toml_dir . '/plugins/denite.rc_post.vim'
'''
hook_add = '''
  execute 'source ' . g:toml_dir . '/plugins/denite.rc.vim'
'''

[[plugins]]
repo = 'rhysd/vim-operator-surround'
on_event = [
   'BufRead',
   'BufNewFile'
]
depends = 'vim-operator-user'
hook_add= '''
  execute 'source ' . g:toml_dir . '/plugins/vim-operator-surround.rc.vim'
'''

[[plugins]]
repo = 'kana/vim-operator-user'

[[plugins]]
repo = 'w0rp/ale'
hook_source = '''
  execute 'source ' . g:toml_dir . '/plugins/ale.rc.vim'
'''

[[plugins]]
repo = 'osyo-manga/vim-precious'
depends = ['context_filetype.vim']
on_event = [
   'BufRead',
   'BufNewFile'
]

[[plugins]]
repo = 'maximbaz/lightline-ale'
on_ft = [
  'go',
  'python',
  'javascript',
  'html',
  'css',
  'markdown',
  'make',
  'yaml.ansible',
  'yaml',
  'toml',
]
depends = ['ale']
hook_add = '''
  execute 'source ' . g:toml_dir . '/plugins/lightline-ale.rc.vim'
'''

[[plugins]]
repo ='Shougo/context_filetype.vim'

[[plugins]]
repo = 'Shougo/neco-vim'

[[plugins]]
repo = 'Shougo/deoplete.nvim'
on_event = ['InsertEnter']
depends = [
  'neosnippet.vim',
  'neco-look',
  'neco-syntax',
  'deoplete-vim-lsp',
]
hook_source = '''
  execute 'source ' . g:toml_dir . '/plugins/deoplete.rc.vim'
'''

[[plugins]]
repo ='Shougo/neosnippet.vim'
depends = [
  'context_filetype.vim',
  'vim-snippets',
  'neosnippet-snippets'
]
hook_add = '''
  execute 'source ' . g:toml_dir . '/plugins/neosnippet.rc.vim'
'''

[[plugins]]
repo = 'lighttiger2505/deoplete-vim-lsp'
depends = [
  'vim-lsp'
]

[[plugins]]
repo = 'prabirshrestha/vim-lsp'
on_ft = [
  'python',
  'yaml',
  'yaml-ansible'
]
depends = [
  'async.vim'
]
hook_add = '''
  execute 'source ' . g:toml_dir . '/plugins/vim-lsp.rc.vim'
'''

[[plugins]]
repo ='Shougo/neomru.vim'

[[plugins]]
repo = 'prabirshrestha/async.vim'
