[[plugins]]
repo = 'Shougo/neocomplete.vim'
if = "has('lua') && (v:version < 800 && !has('nvim') || !has('python3'))"
on_event = ['InsertEnter']
hook_add = '''
  execute 'source ' . fnamemodify(g:dein#_vimrcs[1], ':h') . '/plugins/neco.rc.vim'
'''

[[plugins]]
repo = 'Shougo/deoplete.nvim'
if = "has('python3') && (v:version >= 800 || has('nvim'))"
on_event = ['InsertEnter']
hook_source = '''
  execute 'source ' . fnamemodify(g:dein#_vimrcs[1], ':h') . '/plugins/deoplete.rc.vim'
'''

[[plugins]]
repo = 'Shougo/neosnippet.vim'
on_event = ['InsertEnter']
on_ft = ['snippet']
depends = ['neosnippet-snippets']
hook_add = '''
  execute 'source ' . fnamemodify(g:dein#_vimrcs[1], ':h') . '/plugins/neosnippet.rc.vim'
'''

[[plugins]]
repo = 'ujihisa/neco-look'
on_event = ['InsertEnter']

[[plugins]]
repo = 'pocke/neco-gh-issues'
on_event = ['InsertEnter']

[[plugins]]
repo = 'Shougo/neco-syntax'
on_event = ['InsertEnter']

[[plugins]]
repo = 'rhysd/vim-operator-surround'
on_map = {n = '<Plug>'}
hook_add= '''
  execute 'source ' . fnamemodify(g:dein#_vimrcs[1], ':h') . '/plugins/vim-operator-surround.rc.vim'
'''

[[plugins]]
repo = 'zchee/deoplete-jedi'
on_ft = 'python'
if = "has('nvim')"
depends = ['deoplete.nvim']

[[plugins]]
repo = 'davidhalter/jedi-vim'
on_ft = 'python'
if = "has('python3')"
hook_source = '''
  execute 'source ' . fnamemodify(g:dein#_vimrcs[1], ':h') . '/plugins/jedi-vim.rc.vim'
'''

[[plugins]]
repo = 'davidhalter/jedi-vim'
on_ft = 'python'
if = "!has('python3') && has('python') && has('lua')"
hook_source = '''
  execute 'source ' . fnamemodify(g:dein#_vimrcs[1], ':h') . '/plugins/jedi-vim_vim8.rc.vim'
'''
hook_post_update = '''
  git submodule update --init
'''
